spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/laboratorio
    username: laboratorio
    password: laboratorio
    driverClassName: org.postgresql.Driver

security:
  jwt:
    secret: aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj1YSFhzcW9pVk9fOA==
    validity: 43200 # 30 days in minutes: 30 * 24 * 60
