spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/laboratorio
    username: laboratorio
    password: laboratorio
    driverClassName: org.postgresql.Driver
